version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env 
    volumes:
      - /mnt/data/media:/mnt/data/media
    command: gunicorn goal.wsgi:application --bind 0.0.0.0:8000
