# Generated by Django 5.0.6 on 2024-05-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('publication', 'Publication'), ('training_manual', 'Training_Manual')], default='publication', max_length=20),
        ),
    ]
