# Generated by Django 5.0.6 on 2024-05-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_resources_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='link',
            field=models.URLField(default='#', max_length=250, null=True),
        ),
    ]
