# Generated by Django 5.0.6 on 2024-07-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teammember_alter_resources_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='upcoming',
        ),
        migrations.AddField(
            model_name='workshop',
            name='key_takeaways',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=30),
        ),
        migrations.AddField(
            model_name='workshop',
            name='organised_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='speakers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
