# Generated by Django 5.0.6 on 2024-07-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_workshop_coordinator_remove_workshop_upcoming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_study',
            name='study_area',
            field=models.CharField(max_length=100),
        ),
    ]
