# Generated by Django 5.0.6 on 2024-06-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_image_case_study_images_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='case_study_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.case_study'),
        ),
        migrations.AlterField(
            model_name='image',
            name='workshop_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.workshop'),
        ),
    ]
