# Generated by Django 5.0.6 on 2024-06-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_image_case_study_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_study',
            name='study_area',
            field=models.CharField(max_length=130),
        ),
    ]
