# Generated by Django 5.0.6 on 2024-06-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_case_study_study_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Case_Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=True, upload_to='images/all/')),
                ('case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.case_study')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=True, upload_to='images/all/')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.workshop')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
