# Generated by Django 5.0.6 on 2024-07-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_case_study_study_area'),
        ('core', '0010_image_case_study_image_workshop_delete_image'),
    ]

    operations = [
    ]
