# Generated by Django 5.0.6 on 2024-07-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20240726_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_study',
            name='study_area',
            field=models.CharField(max_length=130),
        ),
    ]
