# Generated by Django 5.0.6 on 2024-07-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_case_study_study_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/resources/'),
        ),
    ]
