# Generated by Django 5.0.6 on 2024-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_case_study_study_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_case_study',
            name='caption',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image_case_study',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image_workshop',
            name='caption',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image_workshop',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
