# Generated by Django 5.0.6 on 2024-07-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_image_case_study_caption_image_case_study_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/team_member/'),
        ),
    ]
