# Generated by Django 5.0.6 on 2024-07-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_resources_link'),
        ('core', '0014_teammember_bg_image'),
    ]

    operations = [
    ]
