# Generated by Django 5.0.6 on 2024-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_theme_casestudythemedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('publication', 'Publication'), ('training_manual', 'Training_Manual'), ('working_papers ', 'Working_Papers'), ('policy_briefs', 'Policy_Briefs')], default='publication', max_length=30),
        ),
    ]
