# Generated by Django 5.0.6 on 2024-08-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20240726_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('description', models.TextField()),
                ('img1', models.ImageField(null=True, upload_to='images/about/')),
                ('img2', models.ImageField(null=True, upload_to='images/about/')),
                ('img3', models.ImageField(null=True, upload_to='images/about/')),
                ('img4', models.ImageField(null=True, upload_to='images/about/')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_image', models.ImageField(upload_to='images/general/')),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resources',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='contact',
        ),
        migrations.AddField(
            model_name='case_study',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='apn_profile_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='website_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_case_study',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_case_study',
            name='image',
            field=models.ImageField(default=True, upload_to='images/case_study/'),
        ),
        migrations.AlterField(
            model_name='image_workshop',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_workshop',
            name='image',
            field=models.ImageField(default=True, upload_to='images/workshop/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('publication', 'Publication'), ('training_tool', 'Training Tool')], default='publication', max_length=30),
        ),
        migrations.CreateModel(
            name='CollaboratingInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='images/logos/')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='core.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudyThemeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=True, upload_to='images/theme/')),
                ('caption', models.TextField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_themes_image', to='core.case_study')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_themes_image', to='core.theme')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudyThemeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_themes', to='core.case_study')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_themes', to='core.theme')),
            ],
        ),
    ]
