# Generated by Django 5.0.6 on 2024-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_about_homepage_stories_theme_remove_resources_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
