# Generated by Django 5.0.6 on 2024-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
