# Generated by Django 5.0.6 on 2024-08-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_teammember_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_case_study',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_workshop',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
