# Generated by Django 5.0.6 on 2024-09-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('publication', 'Publication'), ('training_tool', 'Training Tool'), ('training_tool', 'Training Tool')], default='publication', max_length=30),
        ),
    ]
