# Generated by Django 5.0.6 on 2024-07-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_resources_category'),
        ('core', '0018_remove_teammember_contact_and_more'),
    ]

    operations = [
    ]
