# Generated by Django 5.0.6 on 2024-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_resources_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=30),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='venue',
            field=models.CharField(max_length=500),
        ),
    ]
