# Generated by Django 5.0.6 on 2024-08-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_image_case_study_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_study',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
