# Generated by Django 5.0.6 on 2025-03-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_workshop_mode_alter_workshop_title_and_more'),
        ('core', '0020_case_study_thumbnail_workshop_thumbnail_and_more'),
    ]

    operations = [
    ]
