# Generated by Django 5.0.6 on 2024-08-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_case_study_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_image', models.ImageField(upload_to='images/all/')),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratingInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='images/logos/')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='core.homepage')),
            ],
        ),
    ]
