# Generated by Django 5.0.6 on 2024-08-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_homepage_collaboratinginstitute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='image',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='map_image',
            field=models.ImageField(upload_to='images/general/'),
        ),
        migrations.AlterField(
            model_name='image_case_study',
            name='image',
            field=models.ImageField(default=True, upload_to='images/case_study/'),
        ),
        migrations.AlterField(
            model_name='image_workshop',
            name='image',
            field=models.ImageField(default=True, upload_to='images/workshop/'),
        ),
    ]
