# Generated by Django 5.0.6 on 2025-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20250306_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/workshops/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
