# Generated by Django 5.0.6 on 2025-08-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_stories_pdf_workshop_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_study',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/case_study/maps/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
