# Generated by Django 5.0.6 on 2025-09-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_case_study_map_image_workshop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='lead_institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='mode',
            field=models.CharField(choices=[('offline', 'In Person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=30),
        ),
    ]
