# Generated by Django 5.0.6 on 2024-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='abstract_img',
            field=models.ImageField(null=True, upload_to='images/general/'),
        ),
    ]
