# Generated by Django 5.0.6 on 2025-09-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_workshop_lead_institution_alter_workshop_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudythemeimage',
            name='caption',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='image_case_study',
            name='caption',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='image_workshop',
            name='caption',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
