# Generated by Django 5.0.6 on 2025-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_casestudythemeimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/resource/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('publication', 'Publication'), ('training_tool', 'Training Tool'), ('training_tool', 'Training Tool'), ('flashcard', 'Flashcard'), ('map', 'Map')], default='publication', max_length=30),
        ),
    ]
