# Generated by Django 5.0.6 on 2024-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_about_abstract_img_about_img1_about_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='website_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('publication', 'Publication'), ('training_tool', 'Training Tool')], default='publication', max_length=30),
        ),
    ]
