# Generated by Django 5.0.6 on 2025-09-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_resources_image_alter_resources_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('publication', 'Publication'), ('training_tool', 'Training Tool'), ('flashcard', 'Flashcard'), ('map', 'Map')], default='publication', max_length=30),
        ),
        migrations.AlterField(
            model_name='resources',
            name='date_of_publishing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='publisher',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
