# Generated by Django 5.0.6 on 2025-09-26 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_resources_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='date_of_publishing',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resources',
            name='publisher',
            field=models.CharField(default='Publisher', max_length=25),
        ),
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
