# Generated by Django 5.0.6 on 2024-08-16 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_theme_casestudythemedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyThemeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(default=True, upload_to='images/theme/')),
                ('caption', models.TextField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.case_study')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.theme')),
            ],
        ),
    ]
