# Generated by Django 5.0.6 on 2025-09-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_resources_date_of_publishing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='date_of_publishing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='publisher',
            field=models.CharField(max_length=25),
        ),
    ]
