# Generated by Django 5.0.6 on 2024-08-16 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_casestudythemeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudythemeimage',
            name='description',
        ),
        migrations.AlterField(
            model_name='casestudythemeimage',
            name='case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_themes_image', to='core.case_study'),
        ),
        migrations.AlterField(
            model_name='casestudythemeimage',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_themes_image', to='core.theme'),
        ),
    ]
