# Generated by Django 5.0.6 on 2025-09-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_resources_date_of_publishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/workshops/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='date_of_publishing',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='publisher',
            field=models.CharField(max_length=25, verbose_name='Publisher/Source'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('collaborator', 'Collaborator'), ('research_associate', 'Research Associate'), ('community_trainer', 'Community Knowledge Partner'), ('intern', 'Intern'), ('student', 'Classroom Integration Partner'), ('icimod_huc_partners', 'HUC-ICIMOD Partner')], max_length=30),
        ),
    ]
